CREATE TABLE dialog (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONSTRAINT pk_dialog PRIMARY KEY (id)
);

CREATE TABLE dialog2user (
  dialog_id BIGINT NOT NULL,
  person_id INTEGER NOT NULL,
  CONSTRAINT pk_dialog2user PRIMARY KEY (dialog_id, person_id)
);

ALTER TABLE message ADD dialog_id BIGINT;

ALTER TABLE person ADD CONSTRAINT uc_person_e_mail UNIQUE (e_mail);

ALTER TABLE message ADD CONSTRAINT FK_MESSAGE_ON_DIALOG FOREIGN KEY (dialog_id) REFERENCES dialog (id);

ALTER TABLE dialog2user ADD CONSTRAINT fk_dia_on_dialog FOREIGN KEY (dialog_id) REFERENCES dialog (id);

ALTER TABLE dialog2user ADD CONSTRAINT fk_dia_on_person FOREIGN KEY (person_id) REFERENCES person (id);